kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive --remote

- name: build
  image: alpine
  environment:
    CNAME: arvela.pt
  commands:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.55.0/hugo_0.55.0_Linux-64bit.tar.gz
  - tar xzvf hugo_0.55.0_Linux-64bit.tar.gz
  - ./hugo
  - echo -n "arvela.pt" > public/CNAME

- name: publish
  image: docker:git
  environment:
    NAME: Drone.io CI
    EMAIL: drone@localhost
    GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    SSH_KEY:
      from_secret: github_deploy_key
  commands:
  - export ORIGIN_URL="$(git remote get-url origin)"
  - eval $(ssh-agent)
  - echo "$SSH_KEY" | ssh-add -
  - pushd public
  - git init
  - git remote add origin $ORIGIN_URL
  - git add .
  - git -c user.name="$NAME" commit -m "Deploy website to Github Pages"
  - git push -f origin master:gh-pages1
  when:
    branch:
    - master
    event:
    - push
